apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xyq732mz2-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xyq732mz2-go 
  name: xyq732mz2-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xyq732mz2-go 
